version: '3.6'

services:

  django:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: iogt
      DB_HOST: database
      DB_PORT: '5432'
      DJANGO_SETTINGS_MODULE: iogt.settings.docker_compose_dev
      COMMIT_HASH: asdfghjkl
      WAGTAILTRANSFER_SECRET_KEY: wagtailtransfer-secret-key
      WAGTAILTRANSFER_SOURCE_NAME: iogt_global
      WAGTAILTRANSFER_SOURCE_BASE_URL: https://example.com/wagtail-transfer/
      WAGTAILTRANSFER_SOURCE_SECRET_KEY: wagtailtransfer-source-secret-key
      BASE_URL: 'http://localhost:5000'
      VAPID_PUBLIC_KEY: ''
      VAPID_PRIVATE_KEY: ''
      VAPID_ADMIN_EMAIL: ''
      COMMENTS_COMMUNITY_MODERATION: 'enable'
      COMMENT_MODERATION_CLASS: 'comments.clients.AlwaysApproveModerator'
      BLACKLISTED_WORDS: ''
      SUPERSET_BASE_URL: ''
      SUPERSET_DATABASE_NAME: ''
      SUPERSET_USERNAME: ''
      SUPERSET_PASSWORD: ''
      PUSH_NOTIFICATION: 'enable'
      JQUERY: 'enable'
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - ./:/app/
    ports:
      - "5000:5000"

