version: '3.5'

services:

  django:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      BASE_URL: 'http://localhost:5000'
      DB_CONN_MAX_AGE: '600'
      DB_HOST: db
      DB_NAME: iogt
      DB_PASSWORD: iogt
      DB_PORT: '5432'
      DB_USER: iogt
      DB_SSL_MODE: allow
      DEBUG: enable
      DJANGO_SETTINGS_MODULE: iogt.settings.test
      COMMIT_HASH: asdfghjkl
      SECRET_KEY: secret_key
      WAGTAILTRANSFER_SECRET_KEY: wagtailtransfer-secret-key
      WAGTAILTRANSFER_SOURCE_NAME: iogt_global
      WAGTAILTRANSFER_SOURCE_BASE_URL: https://example.com/wagtail-transfer/
      WAGTAILTRANSFER_SOURCE_SECRET_KEY: wagtailtransfer-source-secret-key
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - ./:/app/
    ports:
      - '5000:5000'

